# -*- coding: utf-8 -*-
"""Question1PythonCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tfLak94HfcAEEUVj6stCa03QzrLdb7aO
"""

import pandas as pd
import seaborn as sns
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('/content/2019 Winter Data Science Intern Challenge Data Set - Sheet1.csv')

data.head()

data.order_amount.describe()

"""we can see above that the mean of the order_amount is 3145.12 which is the mentioned AOV calculated in the question. While calculting AOV we also need to take the total number of orders into account. The correct way to calculate AOV is 
AOV = Total revenue / Total number of orders
"""

df = data.groupby(['shop_id'])['order_amount','total_items'].sum()

df['ARPU'] = df['order_amount'] / df['total_items'] #This stores the ARPU for each shopid

display(df)

ax = sns.scatterplot(x = df.index, y = df.order_amount)

"""There are 2 really significant outliers. Its would cleary effect further analysis if ignored. Since the question mentions affordable shoes i will remove the shop ids with the significantly large revenues"""

z_score = np.abs(stats.zscore(df))

"""We are caluclating the z-score for the table and dropping every any row that has a z-score above 3"""

z_score

df = df[(z_score < 3).all(axis=1)]

df = pd.concat([df,data['shop_id'].value_counts() ], axis = 1)

df.columns = ['Total_revenue', 'Total_items', 'ARPU', 'Total_no_of_orders']
df.index.names = ['shop_id']

df['AOV']  = df.Total_revenue/df.Total_no_of_orders #AOV for each shop id

display(df)

print('Mean AOV:', df.AOV.mean())
print('Mean ARPU for all shops:', df.ARPU.mean())

plt.figure(figsize=(30,5))
ax = sns.barplot(x = df.index, y = df.ARPU)

plt.show()